# Generated by Django 3.1 on 2020-08-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IIdle', '0002_auto_20200825_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='completed_bachelors',
            field=models.BooleanField(default=False),
        ),
    ]
